version: 2
updates:
  # 1. Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Assign a specific user to review these PRs
    reviewers:
      - "CodeWithSushil"

  # 2. Update Composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    # You can also set labels to help organize PRs
    labels:
      - "dependencies"
      - "php"
    reviewers:
      - "CodeWithSushil"
